### PR TITLE
Change url of Tabler Icons

### PR DESCRIPTION
**Pull request by codecalm**
Official website of Tabler Icons is tabler-icons.io. tablericons.com is in no way associated with our project

Paweł,
author of Tabler Icons

### CODE REVIEW

**Comment by codecalm** [comment]
That person (Csaba Kissi) created a page that bears a false resemblance to the official Tabler Icons website: https://tabler-icons.io and generates false reach and misleads users through it. Moreover, it is outdated and falsely implies that the author of the icons is Csaba Kissi, not me. 

It would be nice if you would make a correction. Thank you for your understanding, I have been creating icons for free and open source for almost 2 years and I feel very sad when a stranger makes popularity by impersonating the author.

**Comment by hkalant** [comment]
Hi, I'm not sure how he "falsely implies that the author of the icons is Csaba Kissi"?

Because at the bottom of his page, he clearly says that **Paweł Kuna is the creator of the icons** and Csaba Kissi is the creator of the tablericons.com website.

So he is attributing you as the creator.

Also you are making your icons available with an MIT license, which allows me to take your icons and do whatever I want without restrictions or limitation. Is that not correct?

The only issue with tablericons.com is that he has not included the link to your MIT license which is required. You may want to contact him about that. Since he included your name as the creator I don't see he wouldn't want to include a link to the license.

Please let me know if I have misunderstood.

Many thanks

**Comment by codecalm** [comment]
Many people write to me why there are no icons that are already in the package, which are not on tablericons.com. Many people think that that person is the author of those icons. I have created icons that are free and I would like people to have one source from where they can download icons.

**Comment by hkalant** [comment]
Thanks, I have removed tablericons.com.

**Pull request merged**
